### ISSUE TITLE
diakritika ˇ´

### ISSUE THREAD

**Issue by Kuba799500** [czvojtektomas/keysniper#3]
Ahoj, tentokrát je to dost komplikovanější bug, na který jsem sám nenalezl řešení - jedná se o ručně psané háčky a čárky, např. ď ť ň, kdy napřed musíš zmáčknout shift a klávesu nalevo od backspace, čímž se udělá háček, a následně napsat dané písmeno. KeySniper bohužel detekuje pouze zmáčknutou klávesu písmena bez háčku, což znamená že se může zaseknout uprostřed textu, nebo i hned na začátku a znemožňuje tak bezchybné psaní a další funkce.
Co jsem se koukal, tak to asi bez většího zásahu do kódu nepůjde, takže budu držet palce! ✊ :)

**Comment by vojtektomascz** [comment]
Ahoj, na problém jsem během testování nenarazil. Mohl by jsi mi tvůj problém popsat důkladněji?

**Comment by Kuba799500** [comment]
Ahoj, chyba se projevuje od lekce 48. Jinak jsem myslím už všechno napsal v předchozím komentáři…
Jedině co, tak to mám na Macu (Chrome i Safari) tak nevím, jestli je to na win v pohodě… - vyzkouším zítra v IKT 😂
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/67057136/166806745-0ea0f9e5-1876-4f99-bf37-c39f1dfed8f0.png">

**Comment by Kuba799500** [comment]
Teď zjišťuji, že na Windows to funguje - tedy alespoň z části:
Když při zapnutém bezchybném psaní napíšeš háček a poté napíšeš špatné písmeno, tak už nejde opravit - jediná možnost je bezchybné psaní vypnout a napsat správný znak. Pak se ale stane to, co se stalo na obrázku nahoře - KeySniper se zacyklí a bezchybné psaní nefunguje.
