### ISSUE TITLE
simulované odeslání - chybovost

### ISSUE THREAD

**Issue by Kuba799500** [czvojtektomas/keysniper#4]
Ahoj,
opět další chyba - když zadáváš chybovost při simulovaném odeslání snímku, tak se ignorují čísla za čárkou. Takže když chceš napsat třeba 0.50, tak se místo toho dá 0. To stejné i s 1.56, i vyššími čísly (pro testování)…

**Comment by czvojtektomas** [comment]
Opraveno

**Comment by Kuba799500** [comment]
Ahoj, ještě bych pro jistotu přidal nahrazení desetinné čárky tečkou…
`parseFloat(prompt("Zadejte chybovost:").replace(",", ".")))`
Jinak díky, že reaguješ a opravuješ moje podměty na chyby :)
